# Please keep AllCops, Bundler, Layout, Style, Metrics groups and then order cops
# alphabetically
#
# References:
#   * https://github.com/bbatsov/ruby-style-guide
#   * https://rubocop.readthedocs.io/
#
# This configuration is for Hanami 2.x and Rubocop 0.91+
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/master/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  ExtraDetails: false
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "vendor/**/.*" # See https://github.com/bbatsov/rubocop/issues/4832
