# Please keep AllCops, Bundler, Layout, Style, Metrics groups and then order cops
# alphabetically
#
# References:
#   * https://github.com/bbatsov/ruby-style-guide
#   * https://rubocop.readthedocs.io/
#
# This configuration is for Hanami 2.x and Rubocop ~> 1.0
AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "vendor/**/.*" # See https://github.com/bbatsov/rubocop/issues/4832
Bundler/OrderedGems:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
Gemspec/OrderedDependencies:
  Enabled: false
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*_spec.rb"
Layout/SpaceInLambdaLiteral:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space
Lint/AssignmentInCondition:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/EmptyClass:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: true
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 12
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/MethodName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: exception
Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method
Style/AndOr:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - "spec/**/*_spec.rb"
Style/ConditionalAssignment:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/GuardClause:
  Enabled: false
Style/HashConversion:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RedundantAssignment:
  Enabled: true
Style/RedundantConstantBase:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RegexpLiteral:
  Enabled: false
Style/SlicingWithRange:
  Enabled: true
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
Style/SymbolArray:
  Exclude:
    - "spec/**/*_spec.rb"
Style/TrailingUnderscoreVariable:
  Enabled: false
