# Please keep AllCops, Bundler, Layout, Style, Metrics groups and then order cops
# alphabetically
#
# References:
#   * https://github.com/bbatsov/ruby-style-guide
#   * https://rubocop.readthedocs.io/
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.3
Bundler/OrderedGems:
  Enabled: false
Gemspec/OrderedDependencies:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "tmp/**/*"
Metrics/LineLength:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
# We should enforce in Hanami 2.0
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
# We should enforce double quotes in Hanami 2.0
Style/StringLiterals:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
