# Please keep AllCops, Bundler, Layout, Style, Metrics groups and then order cops
# alphabetically
#
# References:
#   * https://github.com/bbatsov/ruby-style-guide
#   * https://rubocop.readthedocs.io/
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/master/.rubocop.yml
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "vendor/**/*"
    - "vendor/**/.*" # See https://github.com/bbatsov/rubocop/issues/4832
Gemspec/OrderedDependencies:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
